// Auto-generated by scripts/generate-commandcode-catalog.mjs
// Do not edit manually. Regenerate with:
//   node scripts/generate-commandcode-catalog.mjs && npm run format
// Generated: 2026-10-02T15:50:44.919Z
// Model count: 85

import type { NormalizedOpenAIModel } from './shared/openai-models'

export const COMMANDCODE_CATALOG: NormalizedOpenAIModel[] = [
  { id: 'claude-fable-5', name: 'Claude Fable 5', context_length: 1_000_000 },
  { id: 'claude-fable-5-1', name: 'Claude Fable 5.1', context_length: 1_000_000 },
  { id: 'claude-haiku-4-5-20251001', name: 'Claude Haiku 4.5', context_length: 200_000 },
  { id: 'claude-opus-4-7', name: 'Claude Opus 4.7', context_length: 1_000_000 },
  { id: 'claude-opus-4-8', name: 'Claude Opus 4.8', context_length: 1_000_000 },
  { id: 'claude-opus-5', name: 'Claude Opus 5', context_length: 1_000_000 },
  { id: 'claude-opus-5-5', name: 'Claude Opus 5.5', context_length: 1_000_000 },
  { id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6', context_length: 1_000_000 },
  { id: 'claude-sonnet-5', name: 'Claude Sonnet 5', context_length: 1_000_000 },
  { id: 'claude-sonnet-5-5', name: 'Claude Sonnet 5.5', context_length: 1_000_000 },
  {
    id: 'deepseek/deepseek-v4-flash',
    name: 'DeepSeek V4 Flash (latest)',
    context_length: 1_000_000
  },
  {
    id: 'deepseek/deepseek-v4-flash-fast',
    name: 'DeepSeek V4 Flash Fast',
    context_length: 1_000_000
  },
  {
    id: 'deepseek/deepseek-v4-flash-vision-exp',
    name: 'DeepSeek V4 Flash Vision (exp)',
    context_length: 1_000_000
  },
  { id: 'deepseek/deepseek-v4-pro', name: 'DeepSeek V4 Pro (latest)', context_length: 1_000_000 },
  { id: 'deepseek/deepseek-v4.1-flash', name: 'DeepSeek V4.1 Flash', context_length: 1_000_000 },
  {
    id: 'deepseek/deepseek-v4.1-flash-fast',
    name: 'DeepSeek V4.1 Flash Fast',
    context_length: 1_000_000
  },
  { id: 'google/gemini-3.1-flash-lite', name: 'Gemini 3.1 Flash Lite', context_length: 1_000_000 },
  { id: 'google/gemini-3.5-flash', name: 'Gemini 3.5 Flash', context_length: 1_000_000 },
  { id: 'google/gemini-3.5-flash-lite', name: 'Gemini 3.5 Flash Lite', context_length: 1_000_000 },
  { id: 'google/gemini-3.6-flash', name: 'Gemini 3.6 Flash', context_length: 1_000_000 },
  { id: 'google/gemini-3.7-flash', name: 'Gemini 3.7 Flash', context_length: 1_048_576 },
  { id: 'google/gemini-3.8-flash', name: 'Gemini 3.8 Flash', context_length: 1_000_000 },
  { id: 'gpt-5.3-codex', name: 'GPT-5.3 Codex', context_length: 400_000 },
  { id: 'gpt-5.4', name: 'GPT-5.4', context_length: 400_000 },
  { id: 'gpt-5.4-mini', name: 'GPT-5.4 Mini', context_length: 400_000 },
  { id: 'gpt-5.5', name: 'GPT-5.5', context_length: 400_000 },
  { id: 'gpt-5.6-luna', name: 'GPT-5.6 Luna', context_length: 1_050_000 },
  { id: 'gpt-5.6-sol', name: 'GPT-5.6 Sol', context_length: 1_050_000 },
  { id: 'gpt-5.6-terra', name: 'GPT-5.6 Terra', context_length: 1_050_000 },
  { id: 'gpt-6-astra', name: 'GPT-6 Astra', context_length: 1_050_000 },
  { id: 'gpt-6-luna', name: 'GPT-6 Luna', context_length: 1_050_000 },
  { id: 'gpt-6-sol', name: 'GPT-6 Sol', context_length: 1_050_000 },
  { id: 'gpt-6.1-sol', name: 'GPT-6.1 Sol', context_length: 1_050_000 },
  {
    id: 'inclusionai/ling-3.0-flash-sante:free',
    name: 'Ling 3.0 Flash Sante',
    context_length: 262_144
  },
  { id: 'inclusionai/ling-3.1-flash:free', name: 'Ling 3.1 Flash', context_length: 262_144 },
  { id: 'meituan/LongCat-2.0', name: 'LongCat 2.0', context_length: 1_048_576 },
  { id: 'meta/muse-spark-1.1', name: 'Muse Spark 1.1', context_length: 1_048_576 },
  { id: 'meta/muse-spark-1.2', name: 'Muse Spark 1.2', context_length: 1_048_576 },
  {
    id: 'meta/muse-spark-1.2-contributor',
    name: 'Muse Spark 1.2 Contributor',
    context_length: 1_048_576
  },
  { id: 'meta/muse-spark-1.3', name: 'Muse Spark 1.3', context_length: 1_048_576 },
  {
    id: 'meta/muse-spark-1.3-contributor',
    name: 'Muse Spark 1.3 Contributor',
    context_length: 1_048_576
  },
  { id: 'MiniMaxAI/MiniMax-M2.5', name: 'MiniMax M2.5', context_length: 200_000 },
  { id: 'MiniMaxAI/MiniMax-M2.7', name: 'MiniMax M2.7', context_length: 200_000 },
  { id: 'MiniMaxAI/MiniMax-M3', name: 'MiniMax M3', context_length: 1_000_000 },
  { id: 'moonshotai/Kimi-K2.5', name: 'Kimi K2.5', context_length: 256_000 },
  { id: 'moonshotai/Kimi-K2.6', name: 'Kimi K2.6', context_length: 256_000 },
  { id: 'moonshotai/Kimi-K2.7-Code', name: 'Kimi K2.7 Code', context_length: 256_000 },
  {
    id: 'moonshotai/Kimi-K2.7-Code-Highspeed',
    name: 'Kimi K2.7 Code HighSpeed',
    context_length: 262_000
  },
  { id: 'moonshotai/Kimi-K3', name: 'Kimi K3', context_length: 1_000_000 },
  { id: 'nvidia/nemotron-3-ultra-550b-a55b', name: 'Nemotron 3 Ultra', context_length: 1_000_000 },
  { id: 'poolside/laguna-s-2.1-free', name: 'Laguna S 2.1', context_length: 256_000 },
  { id: 'Qwen/Qwen3.6-Max-Preview', name: 'Qwen 3.6 Max Preview', context_length: 200_000 },
  { id: 'Qwen/Qwen3.6-Plus', name: 'Qwen 3.6 Plus', context_length: 200_000 },
  { id: 'Qwen/Qwen3.7-Flash', name: 'Qwen 3.7 Flash', context_length: 1_000_000 },
  { id: 'Qwen/Qwen3.7-Max', name: 'Qwen 3.7 Max', context_length: 1_000_000 },
  { id: 'Qwen/Qwen3.7-Plus', name: 'Qwen 3.7 Plus', context_length: 1_000_000 },
  { id: 'Qwen/Qwen3.8-27B', name: 'Qwen 3.8 27B', context_length: 262_144 },
  { id: 'Qwen/Qwen3.8-Flash', name: 'Qwen 3.8 Flash', context_length: 1_000_000 },
  { id: 'Qwen/Qwen3.8-Max', name: 'Qwen 3.8 Max', context_length: 1_000_000 },
  { id: 'Qwen/Qwen3.8-Max-0902', name: 'Qwen 3.8 Max 0902', context_length: 1_000_000 },
  { id: 'Qwen/Qwen3.8-Omni-Flash', name: 'Qwen 3.8 Omni Flash', context_length: 1_000_000 },
  { id: 'sakana/fugu-ultra', name: 'Fugu Ultra', context_length: 1_000_000 },
  { id: 'stealth/space-bunny-alpha', name: 'Space Bunny Alpha', context_length: 1_000_000 },
  { id: 'stepfun/Step-3.5-Flash', name: 'Step 3.5 Flash', context_length: 262_144 },
  { id: 'stepfun/Step-3.7-Flash', name: 'Step 3.7 Flash', context_length: 256_000 },
  { id: 'stepfun/Step-5-Preview', name: 'Step 5 Preview', context_length: 1_000_000 },
  { id: 'tencent/hy3-paid', name: 'Tencent Hy3', context_length: 262_144 },
  { id: 'tencent/hy4-preview', name: 'Tencent Hy4 Preview', context_length: 1_048_576 },
  { id: 'thinkingmachines/inkling', name: 'Inkling', context_length: 256_000 },
  { id: 'thinkingmachines/inkling-small', name: 'Inkling Small', context_length: 1_000_000 },
  { id: 'xai/grok-4.5', name: 'Grok 4.5', context_length: 500_000 },
  { id: 'xai/grok-4.6', name: 'Grok 4.6', context_length: 500_000 },
  { id: 'xai/grok-4.7', name: 'Grok 4.7', context_length: 500_000 },
  { id: 'xiaomi/mimo-v2.5', name: 'MiMo V2.5', context_length: 1_000_000 },
  { id: 'xiaomi/mimo-v2.5-pro', name: 'MiMo V2.5 Pro', context_length: 1_000_000 },
  { id: 'xiaomi/mimo-v2.6-flash', name: 'MiMo V2.6 Flash', context_length: 1_048_576 },
  { id: 'xiaomi/mimo-v2.6-pro', name: 'MiMo V2.6 Pro', context_length: 1_048_576 },
  {
    id: 'xiaomi/mimo-v2.6-pro-ultraspeed',
    name: 'MiMo V2.6 Pro UltraSpeed',
    context_length: 1_048_576
  },
  { id: 'z-ai/glm-5.3-flash', name: 'GLM-5.3 Flash', context_length: 1_048_576 },
  { id: 'z-ai/glm-5.3-flashx', name: 'GLM-5.3 FlashX', context_length: 1_000_000 },
  { id: 'zai-org/GLM-5', name: 'GLM-5', context_length: 200_000 },
  { id: 'zai-org/GLM-5.1', name: 'GLM-5.1', context_length: 200_000 },
  { id: 'zai-org/GLM-5.2', name: 'GLM-5.2', context_length: 1_000_000 },
  { id: 'zai-org/GLM-5.2-Fast', name: 'GLM-5.2 Fast', context_length: 1_000_000 },
  { id: 'zai-org/GLM-5.3', name: 'GLM-5.3', context_length: 1_000_000 }
]
